version: '3.8'

services:
  web:
    image: django-app:latest
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 4 --access-logfile - --error-logfile -
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
    networks:
      - frontend
      - backend
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  duckdns:
    image: linuxserver/duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - SUBDOMAINS=genericinvoice
      - TOKEN=your_duckdns_token
      - LOG_FILE=true
    volumes:
      - ./duckdns:/config
    restart: unless-stopped

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
