version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    volumes:
      - .:/app/djangotemp/project
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

    restart: unless-stopped
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 4 --access-logfile - --error-logfile -

