version: "3.8"

services:
  web:
    image: rahulkakade/experiments:latest
    expose:
      - "8000"
    environment:
      - DEBUG=0
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - MEDIA_ROOT=/app/media           #  ←  Django will use this
    command: >
      gunicorn core.wsgi:application
        --bind 0.0.0.0:8000
        --workers 4
        --access-logfile -
        --error-logfile -
    volumes:
      # Bind‑mount the host folder so anything Django writes survives restarts
      - /home/pi/pdfs:/app/media
    restart: unless-stopped
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d            # your site configs
      - /home/pi/pdfs:/app/media:ro                 # read‑only mount for media
    command: nginx -g "daemon off;"
    restart: always
    networks:
      - frontend
      - backend

networks:
  frontend:
    name: djangotemp_frontend
    driver: bridge
    attachable: true
  backend:
    name: djangotemp_backend
    driver: bridge
