version: '3.8'

services:
  web:
    image: rahulkakade/experiments:latest
    expose:
      - "8000"
    environment:
      - DEBUG=0
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 4 --access-logfile - --error-logfile -
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - frontend
      - backend
    restart: always
    command: nginx -g "daemon off;"

networks:
  frontend:
    name: djangotemp_frontend
    driver: bridge
    attachable: true
  backend:
    name: djangotemp_backend
    driver: bridge
