version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    volumes:
      - .:/app/djangotemp/project  # Mount the entire project directory
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=/app/djangotemp/project/project  # Set the Python path to match the DockerFile
    restart: unless-stopped
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 4 --reload --access-logfile - --error-logfile -