version: '3'

services:
  certbot:
    image: certbot/dns-duckdns
    volumes:
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --dns-duckdns --dns-duckdns-credentials /etc/letsencrypt/duckdns-token.ini -d genericinvoice.duckdns.org
