# Generated by Django 5.1.7 on 2025-07-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('vehicle', '0002_vehicle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='vehicle',
        ),
        migrations.CreateModel(
            name='InvoiceVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.invoice')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
            options={
                'db_table': 'billing_invoice_vehicles',
                'unique_together': {('invoice', 'vehicle')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='invoices', through='billing.InvoiceVehicle', to='vehicle.vehicle'),
        ),
    ]
