# Generated by Django 5.1.7 on 2025-07-05 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_invoice_vehicle_invoicevehicle_and_more'),
        ('vehicle', '0002_vehicle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='vehicles',
        ),
        migrations.AddField(
            model_name='invoice',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicle'),
        ),
        migrations.DeleteModel(
            name='InvoiceVehicle',
        ),
    ]
