# Generated by Django 5.1.7 on 2025-07-05 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_create_gst_table'),
        ('company', '0001_initial'),
        ('product', '0001_initial'),
        ('vehicle', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='company.company'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='plant',
            field=models.ForeignKey(db_column='plant_id', on_delete=django.db.models.deletion.PROTECT, to='vendor.plant'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='vehicle',
            field=models.ForeignKey(blank=True, db_column='vehicle_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicle'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='vendor',
            field=models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.PROTECT, to='vendor.vendor'),
        ),
        migrations.AlterModelTable(
            name='billing',
            table='billing_billing',
        ),
    ]
