# Generated by Django 5.1.7 on 2025-07-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_billing_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20, null=True),
        ),
    ]
