# Generated by Django 5.1.7 on 2025-07-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoice_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_status',
        ),
    ]
