# Generated by Django 5.1.7 on 2025-06-01 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_gst'),
        ('company', '0004_bankdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.bankdetail'),
        ),
    ]
