apiVersion: v1
kind: Service
metadata:
  name: generic-invoice-service
spec:
  type: NodePort
  selector:
    app: generic-invoice-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000